"""
Drug Knowledge Base — UAE MOH aligned.
Contains: drug info, interactions, dosages, UAE-specific regulations.
Used to populate ChromaDB for RAG retrieval.
"""

DRUG_DATABASE = [
    # ── ANTIBIOTICS ────────────────────────────────────────────────────────
    {
        "id": "amoxicillin",
        "name": "Amoxicillin",
        "category": "Antibiotic - Penicillin",
        "brand_names": ["Amoxil", "Trimox", "Moxatag"],
        "uae_available": True,
        "standard_doses": {"adult": "500mg TID or 875mg BID", "child": "25-50 mg/kg/day"},
        "max_daily_dose": {"adult": "3000mg", "child": "3000mg"},
        "contraindications": ["penicillin allergy", "mononucleosis"],
        "interactions": [
            {"drug": "Warfarin", "severity": "moderate", "effect": "May increase anticoagulant effect"},
            {"drug": "Methotrexate", "severity": "severe", "effect": "Reduced methotrexate clearance — toxicity risk"},
            {"drug": "Oral contraceptives", "severity": "minor", "effect": "May reduce contraceptive effectiveness"},
        ],
        "pregnancy_category": "B",
        "uae_moh_notes": "Available OTC in UAE for minor infections; prescription required for >7 day courses.",
        "knowledge_text": "Amoxicillin 500mg TID for adults. Max 3g/day. Contraindicated in penicillin allergy. Severe interaction with Methotrexate (toxicity). Moderate interaction with Warfarin (increased bleeding risk). Safe in pregnancy (Category B).",
    },
    {
        "id": "azithromycin",
        "name": "Azithromycin",
        "category": "Antibiotic - Macrolide",
        "brand_names": ["Zithromax", "Azee", "Azithral"],
        "uae_available": True,
        "standard_doses": {"adult": "500mg OD day 1, then 250mg OD x4 days", "child": "10 mg/kg day 1, then 5 mg/kg x4 days"},
        "max_daily_dose": {"adult": "500mg"},
        "contraindications": ["QT prolongation history", "liver disease", "macrolide allergy"],
        "interactions": [
            {"drug": "Warfarin", "severity": "moderate", "effect": "Increased INR — monitor closely"},
            {"drug": "Amiodarone", "severity": "severe", "effect": "Fatal QT prolongation risk"},
            {"drug": "Digoxin", "severity": "moderate", "effect": "Increased digoxin levels"},
            {"drug": "Simvastatin", "severity": "moderate", "effect": "Increased risk of myopathy"},
        ],
        "pregnancy_category": "B",
        "uae_moh_notes": "Schedule 3 medication in UAE — prescription mandatory.",
        "knowledge_text": "Azithromycin Z-pack: 500mg day 1, then 250mg x4 days. Severe QT prolongation risk with Amiodarone — CONTRAINDICATED. Monitor Warfarin INR. Avoid in patients with QT prolongation history.",
    },
    {
        "id": "ciprofloxacin",
        "name": "Ciprofloxacin",
        "category": "Antibiotic - Fluoroquinolone",
        "brand_names": ["Cipro", "Ciproxin"],
        "uae_available": True,
        "standard_doses": {"adult": "500mg BID (oral) or 400mg BID (IV)", "child": "Not recommended <18 years"},
        "max_daily_dose": {"adult": "1500mg"},
        "contraindications": ["age <18 years", "tendon disorders", "QT prolongation", "fluoroquinolone allergy"],
        "interactions": [
            {"drug": "Warfarin", "severity": "severe", "effect": "Major INR increase — bleeding risk"},
            {"drug": "Antacids/Calcium", "severity": "moderate", "effect": "Reduced absorption — separate by 2h"},
            {"drug": "Theophylline", "severity": "severe", "effect": "Theophylline toxicity — CNS effects"},
            {"drug": "NSAIDs", "severity": "moderate", "effect": "Increased CNS seizure risk"},
            {"drug": "Amiodarone", "severity": "severe", "effect": "QT prolongation"},
        ],
        "pregnancy_category": "C",
        "uae_moh_notes": "Restricted in UAE — prescription mandatory. Not for children <18 due to cartilage toxicity.",
        "knowledge_text": "Ciprofloxacin 500mg BID adults only. Contraindicated <18 years — cartilage damage risk. Severe interaction: Warfarin (major bleeding), Theophylline (toxicity), Amiodarone (QT prolongation). Category C pregnancy — avoid.",
    },
    # ── CARDIOVASCULAR ────────────────────────────────────────────────────
    {
        "id": "warfarin",
        "name": "Warfarin",
        "category": "Anticoagulant",
        "brand_names": ["Coumadin", "Jantoven"],
        "uae_available": True,
        "standard_doses": {"adult": "Individualized — INR guided, usually 2-10mg/day"},
        "max_daily_dose": {"adult": "Individualized"},
        "contraindications": ["active bleeding", "pregnancy", "severe hepatic impairment", "uncontrolled hypertension"],
        "interactions": [
            {"drug": "Aspirin", "severity": "severe", "effect": "Major bleeding risk"},
            {"drug": "Amoxicillin", "severity": "moderate", "effect": "Increased anticoagulant effect"},
            {"drug": "Ciprofloxacin", "severity": "severe", "effect": "Major INR increase"},
            {"drug": "Azithromycin", "severity": "moderate", "effect": "Increased INR"},
            {"drug": "Ibuprofen", "severity": "severe", "effect": "Gastrointestinal bleeding risk"},
            {"drug": "Omeprazole", "severity": "moderate", "effect": "Slightly increased Warfarin effect"},
            {"drug": "Simvastatin", "severity": "moderate", "effect": "Increased Warfarin effect"},
        ],
        "pregnancy_category": "X",
        "uae_moh_notes": "High-alert medication in UAE — dispensed only with valid prescription and INR monitoring.",
        "knowledge_text": "Warfarin is a HIGH ALERT anticoagulant. Dose is INR-guided. Pregnancy Category X — absolute contraindication. Severe interaction with Aspirin (fatal bleeding), Ciprofloxacin (major INR rise), Ibuprofen (GI bleeding). Moderate interaction with most antibiotics. Requires regular INR monitoring.",
    },
    {
        "id": "amlodipine",
        "name": "Amlodipine",
        "category": "Calcium Channel Blocker - Antihypertensive",
        "brand_names": ["Norvasc", "Amlor"],
        "uae_available": True,
        "standard_doses": {"adult": "5-10mg OD", "elderly": "2.5-5mg OD"},
        "max_daily_dose": {"adult": "10mg"},
        "contraindications": ["cardiogenic shock", "severe aortic stenosis", "unstable angina"],
        "interactions": [
            {"drug": "Simvastatin", "severity": "moderate", "effect": "Increase simvastatin exposure — myopathy risk. Max simvastatin 20mg with amlodipine"},
            {"drug": "Cyclosporine", "severity": "moderate", "effect": "Increased cyclosporine levels"},
        ],
        "pregnancy_category": "C",
        "uae_moh_notes": "Widely used in UAE. MOH recommends 5mg starting dose in elderly.",
        "knowledge_text": "Amlodipine 5-10mg once daily for hypertension. Max 10mg/day. Important: when combined with Simvastatin, max Simvastatin dose is 20mg due to myopathy risk. Start elderly at 2.5-5mg.",
    },
    {
        "id": "metformin",
        "name": "Metformin",
        "category": "Antidiabetic - Biguanide",
        "brand_names": ["Glucophage", "Glumetza", "Fortamet"],
        "uae_available": True,
        "standard_doses": {"adult": "500-1000mg BID with meals"},
        "max_daily_dose": {"adult": "2550mg"},
        "contraindications": ["eGFR <30 mL/min", "hepatic impairment", "contrast dye use (hold 48h)", "alcohol abuse"],
        "interactions": [
            {"drug": "Contrast dye", "severity": "severe", "effect": "Lactic acidosis risk — hold 48h before/after contrast"},
            {"drug": "Alcohol", "severity": "severe", "effect": "Lactic acidosis risk"},
            {"drug": "Furosemide", "severity": "moderate", "effect": "Increased metformin levels"},
        ],
        "pregnancy_category": "B",
        "uae_moh_notes": "First-line T2DM medication in UAE MOH guidelines. eGFR monitoring required.",
        "knowledge_text": "Metformin 500-1000mg BID with meals. Max 2550mg/day. HOLD 48 hours before and after contrast dye (severe lactic acidosis risk). Contraindicated if eGFR <30. Monitor renal function. Safe in pregnancy (Category B).",
    },
    {
        "id": "atorvastatin",
        "name": "Atorvastatin",
        "category": "Statin - Lipid Lowering",
        "brand_names": ["Lipitor", "Atorva"],
        "uae_available": True,
        "standard_doses": {"adult": "10-80mg OD at night"},
        "max_daily_dose": {"adult": "80mg"},
        "contraindications": ["active liver disease", "pregnancy", "breastfeeding", "CK elevation"],
        "interactions": [
            {"drug": "Clarithromycin", "severity": "severe", "effect": "Massive statin level increase — rhabdomyolysis risk"},
            {"drug": "Cyclosporine", "severity": "severe", "effect": "10x statin increase — avoid"},
            {"drug": "Gemfibrozil", "severity": "severe", "effect": "Rhabdomyolysis risk"},
            {"drug": "Warfarin", "severity": "moderate", "effect": "Slightly increased Warfarin effect"},
            {"drug": "Amiodarone", "severity": "moderate", "effect": "Increased statin levels"},
        ],
        "pregnancy_category": "X",
        "uae_moh_notes": "Preferred statin per UAE MOH cardiovascular guidelines.",
        "knowledge_text": "Atorvastatin 10-80mg nightly. Pregnancy Category X — absolute contraindication. Severe interaction with Clarithromycin and Cyclosporine (rhabdomyolysis). Monitor CK levels. Category X in pregnancy.",
    },
    {
        "id": "omeprazole",
        "name": "Omeprazole",
        "category": "Proton Pump Inhibitor",
        "brand_names": ["Prilosec", "Losec"],
        "uae_available": True,
        "standard_doses": {"adult": "20-40mg OD before breakfast"},
        "max_daily_dose": {"adult": "40mg (standard); 80mg for Zollinger-Ellison"},
        "contraindications": ["hypomagnesemia (long-term)"],
        "interactions": [
            {"drug": "Clopidogrel", "severity": "moderate", "effect": "Reduced clopidogrel antiplatelet effect — use pantoprazole instead"},
            {"drug": "Methotrexate", "severity": "moderate", "effect": "Increased methotrexate toxicity"},
            {"drug": "Warfarin", "severity": "minor", "effect": "Slightly increased Warfarin effect"},
        ],
        "pregnancy_category": "C",
        "uae_moh_notes": "OTC available in UAE for short courses. Avoid long-term use >8 weeks without review.",
        "knowledge_text": "Omeprazole 20-40mg before breakfast. Important: reduces Clopidogrel effectiveness — prefer Pantoprazole in post-stent patients. Long-term use >8 weeks requires physician review (hypomagnesemia, B12 deficiency risk).",
    },
    {
        "id": "ibuprofen",
        "name": "Ibuprofen",
        "category": "NSAID - Anti-inflammatory",
        "brand_names": ["Brufen", "Advil", "Nurofen"],
        "uae_available": True,
        "standard_doses": {"adult": "400-800mg TID with food", "child": "5-10 mg/kg q6-8h"},
        "max_daily_dose": {"adult": "2400mg (OTC) / 3200mg (Rx)"},
        "contraindications": ["peptic ulcer", "renal impairment", "third trimester pregnancy", "aspirin allergy", "heart failure"],
        "interactions": [
            {"drug": "Warfarin", "severity": "severe", "effect": "GI bleeding and increased anticoagulant effect"},
            {"drug": "Lithium", "severity": "severe", "effect": "Lithium toxicity"},
            {"drug": "Methotrexate", "severity": "severe", "effect": "Methotrexate toxicity"},
            {"drug": "ACE inhibitors", "severity": "moderate", "effect": "Reduced antihypertensive effect; acute kidney injury risk"},
            {"drug": "Aspirin", "severity": "moderate", "effect": "Increased GI bleeding; ibuprofen may reduce aspirin cardioprotective effect"},
            {"drug": "Ciprofloxacin", "severity": "moderate", "effect": "Increased seizure risk"},
        ],
        "pregnancy_category": "C (D in third trimester)",
        "uae_moh_notes": "OTC in UAE. UAE MOH warning: avoid in renal impairment and heart failure.",
        "knowledge_text": "Ibuprofen 400-800mg TID with food. Max 2400mg/day OTC. Severe interactions: Warfarin (major GI bleeding), Lithium (toxicity), Methotrexate (toxicity). Contraindicated in peptic ulcer, renal failure, heart failure. AVOID in third trimester — Category D.",
    },
    {
        "id": "amiodarone",
        "name": "Amiodarone",
        "category": "Antiarrhythmic - Class III",
        "brand_names": ["Cordarone", "Pacerone"],
        "uae_available": True,
        "standard_doses": {"adult": "200mg OD maintenance (after loading)"},
        "max_daily_dose": {"adult": "400mg maintenance"},
        "contraindications": ["thyroid disease", "pulmonary toxicity history", "pregnancy", "iodine allergy"],
        "interactions": [
            {"drug": "Warfarin", "severity": "severe", "effect": "Doubles Warfarin effect — INR must be monitored weekly"},
            {"drug": "Digoxin", "severity": "severe", "effect": "Digoxin toxicity — halve digoxin dose"},
            {"drug": "Simvastatin", "severity": "severe", "effect": "Rhabdomyolysis — max simvastatin 20mg"},
            {"drug": "Ciprofloxacin", "severity": "severe", "effect": "Fatal QT prolongation"},
            {"drug": "Azithromycin", "severity": "severe", "effect": "Fatal QT prolongation"},
            {"drug": "Atorvastatin", "severity": "moderate", "effect": "Increased statin levels"},
        ],
        "pregnancy_category": "D",
        "uae_moh_notes": "Hospital-restricted in UAE. Thyroid, liver, pulmonary monitoring mandatory.",
        "knowledge_text": "Amiodarone 200mg OD maintenance — HIGH ALERT cardiac drug. Severe interactions: Warfarin (doubles INR), Digoxin (toxicity), Ciprofloxacin/Azithromycin (fatal QT prolongation), Simvastatin (rhabdomyolysis). Category D pregnancy. Requires thyroid and pulmonary monitoring.",
    },
    {
        "id": "metoprolol",
        "name": "Metoprolol",
        "category": "Beta-Blocker - Antihypertensive",
        "brand_names": ["Lopressor", "Toprol-XL", "Betaloc"],
        "uae_available": True,
        "standard_doses": {"adult": "25-100mg BID (tartrate) or 25-200mg OD (succinate XL)"},
        "max_daily_dose": {"adult": "400mg"},
        "contraindications": ["bradycardia HR<60", "severe asthma/COPD", "cardiogenic shock", "2nd/3rd degree AV block"],
        "interactions": [
            {"drug": "Verapamil", "severity": "severe", "effect": "Complete heart block risk — avoid combination"},
            {"drug": "Clonidine", "severity": "moderate", "effect": "Rebound hypertension if clonidine stopped first"},
            {"drug": "Insulin", "severity": "moderate", "effect": "Masks hypoglycemia symptoms"},
            {"drug": "Digoxin", "severity": "moderate", "effect": "Additive bradycardia"},
        ],
        "pregnancy_category": "C",
        "uae_moh_notes": "First-line beta-blocker in UAE MOH hypertension guidelines.",
        "knowledge_text": "Metoprolol 25-100mg BID for hypertension/heart failure. AVOID in asthma, COPD, bradycardia, AV block. Severe: Verapamil combination (complete heart block). Moderate: masks hypoglycemia in diabetics taking insulin. Caution stopping — taper gradually.",
    },
    {
        "id": "paracetamol",
        "name": "Paracetamol (Acetaminophen)",
        "category": "Analgesic - Antipyretic",
        "brand_names": ["Panadol", "Tylenol", "Calpol"],
        "uae_available": True,
        "standard_doses": {"adult": "500-1000mg q4-6h", "child": "10-15 mg/kg q4-6h"},
        "max_daily_dose": {"adult": "4000mg (3000mg in elderly/liver disease)", "child": "60mg/kg/day"},
        "contraindications": ["severe hepatic impairment"],
        "interactions": [
            {"drug": "Alcohol", "severity": "severe", "effect": "Hepatotoxicity — avoid >3 units alcohol daily"},
            {"drug": "Warfarin", "severity": "moderate", "effect": "Regular high-dose paracetamol increases INR"},
            {"drug": "Isoniazid", "severity": "moderate", "effect": "Increased hepatotoxicity risk"},
        ],
        "pregnancy_category": "B",
        "uae_moh_notes": "Most commonly dispensed OTC drug in UAE. Overdose is leading cause of acute liver failure.",
        "knowledge_text": "Paracetamol 500-1000mg every 4-6 hours. MAX 4g/day adults (3g/day in elderly/liver disease). Safe in pregnancy (Category B). Alcohol + paracetamol = hepatotoxicity. Overdose: 7.5g+ can cause acute liver failure — check all combination products for hidden paracetamol.",
    },
    {
        "id": "lisinopril",
        "name": "Lisinopril",
        "category": "ACE Inhibitor - Antihypertensive",
        "brand_names": ["Zestril", "Prinivil"],
        "uae_available": True,
        "standard_doses": {"adult": "10-40mg OD", "heart_failure": "5-40mg OD"},
        "max_daily_dose": {"adult": "80mg"},
        "contraindications": ["pregnancy", "bilateral renal artery stenosis", "history of ACE inhibitor angioedema", "hyperkalemia"],
        "interactions": [
            {"drug": "Potassium supplements", "severity": "severe", "effect": "Dangerous hyperkalemia"},
            {"drug": "NSAIDs", "severity": "moderate", "effect": "Reduced antihypertensive effect; AKI risk"},
            {"drug": "Spironolactone", "severity": "severe", "effect": "Severe hyperkalemia"},
            {"drug": "Lithium", "severity": "moderate", "effect": "Increased lithium levels"},
        ],
        "pregnancy_category": "D",
        "uae_moh_notes": "First-line antihypertensive in UAE MOH guidelines. Category D — stop immediately if pregnancy confirmed.",
        "knowledge_text": "Lisinopril 10-40mg once daily. Pregnancy Category D — STOP immediately if patient becomes pregnant. Severe: combined with potassium supplements or Spironolactone causes dangerous hyperkalemia. Monitor K+ and creatinine. Cough is common side effect (switch to ARB).",
    },
    {
        "id": "simvastatin",
        "name": "Simvastatin",
        "category": "Statin - Lipid Lowering",
        "brand_names": ["Zocor", "Simva"],
        "uae_available": True,
        "standard_doses": {"adult": "10-40mg OD at night"},
        "max_daily_dose": {"adult": "40mg (80mg only in longstanding patients)"},
        "contraindications": ["active liver disease", "pregnancy", "CK >10x ULN"],
        "interactions": [
            {"drug": "Amiodarone", "severity": "severe", "effect": "Max simvastatin 20mg — rhabdomyolysis"},
            {"drug": "Amlodipine", "severity": "moderate", "effect": "Max simvastatin 20mg"},
            {"drug": "Clarithromycin", "severity": "severe", "effect": "AVOID — rhabdomyolysis"},
            {"drug": "Cyclosporine", "severity": "severe", "effect": "AVOID — massive statin increase"},
            {"drug": "Gemfibrozil", "severity": "severe", "effect": "AVOID — rhabdomyolysis"},
            {"drug": "Warfarin", "severity": "moderate", "effect": "Increased Warfarin effect"},
        ],
        "pregnancy_category": "X",
        "uae_moh_notes": "UAE MOH: dose cap warnings for simvastatin combinations.",
        "knowledge_text": "Simvastatin 10-40mg nightly. Category X — absolutely contraindicated in pregnancy. Important dose caps: max 20mg with Amiodarone or Amlodipine. AVOID with Clarithromycin, Cyclosporine, Gemfibrozil (rhabdomyolysis). Monitor CK levels.",
    },
    {
        "id": "aspirin",
        "name": "Aspirin",
        "category": "Antiplatelet / Analgesic / NSAID",
        "brand_names": ["Disprin", "Ecotrin", "Aspocid"],
        "uae_available": True,
        "standard_doses": {"antiplatelet": "75-100mg OD", "analgesia": "300-900mg q4-6h", "anti-inflammatory": "3600-5400mg/day"},
        "max_daily_dose": {"adult": "4000mg (anti-inflammatory); 100mg antiplatelet"},
        "contraindications": ["age <16 (Reye syndrome)", "active GI bleed", "severe hepatic impairment", "haemophilia"],
        "interactions": [
            {"drug": "Warfarin", "severity": "severe", "effect": "Major bleeding risk — avoid unless cardiology approved"},
            {"drug": "Ibuprofen", "severity": "moderate", "effect": "Ibuprofen blocks aspirin cardioprotection — take aspirin 2h before"},
            {"drug": "Methotrexate", "severity": "severe", "effect": "Methotrexate toxicity"},
            {"drug": "Clopidogrel", "severity": "moderate", "effect": "Dual antiplatelet — high bleeding risk, usually intentional"},
        ],
        "pregnancy_category": "C (D in third trimester)",
        "uae_moh_notes": "Aspirin <16 years BANNED in UAE (Reye syndrome risk). Low-dose 75mg widely used for CV protection.",
        "knowledge_text": "Aspirin BANNED in patients under 16 (Reye syndrome). Low-dose 75-100mg for antiplatelet. Severe: Warfarin combination (major bleeding). Ibuprofen reduces aspirin cardioprotection. Third trimester Category D. If patient on daily aspirin — check for concurrent NSAIDs.",
    },
    {
        "id": "insulin_glargine",
        "name": "Insulin Glargine",
        "category": "Insulin - Long-acting",
        "brand_names": ["Lantus", "Basaglar", "Toujeo"],
        "uae_available": True,
        "standard_doses": {"adult": "10 units SC OD (titrate to FBS 80-130 mg/dL)"},
        "max_daily_dose": {"adult": "Individualized"},
        "contraindications": ["hypoglycemia"],
        "interactions": [
            {"drug": "Beta-blockers", "severity": "moderate", "effect": "Masks hypoglycemia symptoms except sweating"},
            {"drug": "Alcohol", "severity": "moderate", "effect": "Prolonged hypoglycemia"},
            {"drug": "Corticosteroids", "severity": "moderate", "effect": "Increased insulin requirements"},
            {"drug": "Fluoroquinolones", "severity": "moderate", "effect": "Both hyperglycemia and hypoglycemia reported"},
        ],
        "pregnancy_category": "B",
        "uae_moh_notes": "Cold chain mandatory in UAE. Dispensed with needles per MOH regulations.",
        "knowledge_text": "Insulin Glargine (Lantus) SC once daily. Cold chain required. Moderate: beta-blockers mask hypoglycemia, alcohol prolongs hypoglycemia. Corticosteroids increase insulin requirements significantly. Dispensed with BD needles per UAE pharmacy regulations.",
    },
    {
        "id": "clopidogrel",
        "name": "Clopidogrel",
        "category": "Antiplatelet - P2Y12 inhibitor",
        "brand_names": ["Plavix", "Clopilet"],
        "uae_available": True,
        "standard_doses": {"adult": "75mg OD"},
        "max_daily_dose": {"adult": "75mg (maintenance)"},
        "contraindications": ["active pathological bleeding", "severe hepatic impairment"],
        "interactions": [
            {"drug": "Omeprazole", "severity": "moderate", "effect": "Reduces clopidogrel effect 47% — use Pantoprazole instead"},
            {"drug": "Aspirin", "severity": "moderate", "effect": "Dual antiplatelet — bleeding risk, often intentional"},
            {"drug": "Warfarin", "severity": "severe", "effect": "Triple therapy — very high bleeding risk"},
            {"drug": "NSAIDs", "severity": "moderate", "effect": "GI bleeding risk"},
        ],
        "pregnancy_category": "B",
        "uae_moh_notes": "Mandatory post-PCI in UAE hospitals for 12 months per MOH guidelines.",
        "knowledge_text": "Clopidogrel 75mg once daily antiplatelet. Critical: Omeprazole reduces clopidogrel effect by 47% — prescribe Pantoprazole instead. Post-PCI patients MUST continue for 12 months per UAE MOH guidelines. Triple therapy with Warfarin + Aspirin requires specialist approval.",
    },
]

# ── Drug interaction lookup for quick O(1) access ──────────────────────────

def build_interaction_map():
    """Build bidirectional drug interaction map for quick lookup."""
    interaction_map = {}
    for drug in DRUG_DATABASE:
        drug_name = drug["name"].lower()
        for interaction in drug.get("interactions", []):
            other = interaction["drug"].lower()
            key = tuple(sorted([drug_name, other]))
            if key not in interaction_map:
                interaction_map[key] = {
                    "drugs": [drug["name"], interaction["drug"]],
                    "severity": interaction["severity"],
                    "effect": interaction["effect"],
                }
    return interaction_map

INTERACTION_MAP = build_interaction_map()

DRUG_NAME_INDEX = {drug["name"].lower(): drug for drug in DRUG_DATABASE}
for drug in DRUG_DATABASE:
    for brand in drug.get("brand_names", []):
        DRUG_NAME_INDEX[brand.lower()] = drug
